### ISSUE TITLE
Security Issue: Disable Mutable Tags in ECR

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server#409]
Issue found in Snyk scan of TF Files

##  Path: 

resource > aws_ecr_repository[repository] > image_tag_mutability

## The issue is...

The AWS ECR registry does not enforce immutable tags

## The impact of this is...

Image tags can be modified post deployment

## You can resolve this by...

Set image_tag_mutability attribute to IMMUTABLE

## AC

 - [ ] Disable check in Demo https://github.com/cds-snc/covid-alert-server-demo-terraform/issues/29
 - [ ] Disable check in Staging https://github.com/cds-snc/covid-alert-server-staging-terraform/issues/72
 - [ ] Fix in Prod https://github.com/cds-snc/covid-alert-server-production-terraform/issues/46

**Comment by CalvinRodo** [comment]
On hold as I determine if we need mutable tags for anything

**Comment by CalvinRodo** [comment]
Not going to get to this, will re-open if we do.
